apiVersion: v1
kind: Namespace
metadata:
  name: ao_ocr

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: ao-ocr-deployment
  namespace: ao_ocr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ao-ocr
  template:
    metadata:
      labels:
        app: ao-ocr
    spec:
      containers:
      - name: ao-ocr-container
        image: ao_ocr:latest
        ports:
        - containerPort: 8000

---

apiVersion: v1
kind: Service
metadata:
  name: ao-ocr-service
  namespace: ao_ocr
spec:
  type: NodePort
  selector:
    app: ao-ocr
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
    nodePort: 32888
